<?php include("../basedir.php"); ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="main.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/global.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/google-analytics.js"></script>

<!--

What are you doing?
Get out of my source code, fool!
Go home. You are drunk.


                _,.---.---.---.--.._
            _.-' `--.`---.`---'-. _,`--.._
           /`--._ .'.     `.     `,`-.`-._\
          ||   \  `.`---.__`__..-`. ,'`-._/
     _  ,`\ `-._\   \    `.    `_.-`-._,``-.
  ,`   `-_ \/ `-.`--.\    _\_.-'\__.-`-.`-._`.
 (_.o> ,--. `._/'--.-`,--`  \_.-'       \`-._ \
  `---'    `._ `---._/__,----`           `-. `-\
            /_, ,  _..-'                    `-._\
            \_, \/ ._(
             \_, \/ ._\
              `._,\/ ._\
                `._// ./`-._
         LGB      `-._-_-_.-'


		         (\/)
    ___         o \/
  ."   ". /@) o
<|_______|/`
  UU   UU

-->

<html>
	<head>
		<!-- Bootstrap CDN -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="style.css">
		<title>The Foffbox: Collaborative Music Radio!</title>
	</head>
	<body style="background-color: #e3e3e3;">

		<?php include("../navbar/navbar.phtml"); ?>

		<video id="bg-video" muted autoplay loop>
			<source src="data/vid/video1.mp4" type="video/mp4">
		</video>

		<div id="site-intro">

		</div>

		<div id="site-intro-wrapper">
			<div class="row row-padding-fix">
				<div class="col-md-8 col-md-offset-2">
					<div class="jumbotron">
						<h1>Get ready to drop beats.</h1>
						<h2>The Foffbox is a music playlist: By everyone, for you.</h2>
						
						<div class="row row-padding-fix">
							<div class="col-md-6 col-md-offset-3 well" style="background-color: #D3D3D3 !important;">
								<ul>
									<li><h3><span class="glyphicon glyphicon-music"></span> Get <strong>music</strong> from Youtube.</h3></li>
									<li><h3><span class="glyphicon glyphicon-bullhorn"></span> Express yourself with a <strong>message</strong>.</h3></li>
									<li><h3><span class="glyphicon glyphicon-cloud-upload"></span> <strong>Submit</strong> it to the Foffbox.</h3></li>
									<li><h3><span class="glyphicon glyphicon-headphones"></span> <strong>Rock out to <span id="submission-number">a whole lot of</span> submissions</strong>.</h3></li>
								</ul>
								
								<a id="site-intro-close" class="btn btn-lg btn-block btn-success" data-toggle="modal" data-target="#modal-drop-beats"><strong><span class="glyphicon glyphicon-cloud-upload"></span> Start adding songs!</strong></a>
								<a id="site-intro-radio" class="btn btn-lg btn-block btn-info" href="player"><span class="glyphicon glyphicon-headphones"></span> Take me to the playlist!</a>
							</div>
						</div>
						
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

<div id="modal-drop-beats" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body" style="padding:25px;">

					<!-- Form -->
					<form id="foffbox-form">
						<div id="foffbox-form-group" class="form-group">
							<div class="row">
								<div class="col-md-12">

									<!-- Youtube URL -->
									<label for="drop-beats-url">Youtube URL:</strong></label> <span id="suggestion" class="pull-right field-subtext" data-toggle="tooltip" title="Hello world!">Need a suggestion? <span class="glyphicon glyphicon-question-sign"></span></span>
									<input id="drop-beats-url" type="text" class="form-control" name="youtubeUrl" placeholder="e.g. youtube.com/watch?v=ZZ5LpwO-An4" maxlength="64" pattern="((https:\/\/)|(http:\/\/))?((m.)|(www.))?(youtube.com\/watch\?v=)([a-zA-Z0-9\-\_]){9,12}" required /><br>

									<!-- Message -->
									<label for="message">Include a message:</label> <span id="message-remaining" class="pull-right field-subtext">500 remaining</span>
									<textarea id="message" type="text" class="form-control" name="messageBox" placeholder="Your own special touch." maxlength="500" rows="3" required></textarea><br>

										<?php
											$configMode = 'live';
											$connectionData = require_once("server-config.php");
											$connectionData = $connectionData[$configMode];
											$pdo = new PDO($connectionData['dsn'], $connectionData['username'], $connectionData['password']);
											$sqlStatement = $pdo->prepare("SELECT `id`, `name` FROM `submissions_labels` WHERE `active` = 1");
											$sqlStatement->execute();
											$labelResults = $sqlStatement->fetchAll(PDO::FETCH_ASSOC);
										
											if (!empty($labelResults))
											{
												echo<<<EOT
												<label for="label">How would you label this song? (Optional)</label>
												<select id="label" class="form-control" name="label">
													<option value="0">Let others label it for me</option>
													<optgroup label="----------"></optgroup>
EOT;

													foreach ($labelResults as $labelResult)
													{
														$id = $labelResult['id'];
														$name = $labelResult['name'];
														
														echo("<option value=\"$id\">$name</option>");
													}
												
												echo('</select><br>');
											}
										?>
									
									</select>

									<!-- Loading alert -->
									<div id="alert-loading" class="alert alert-info alert-hide"><img src="data/img/loading.gif"/> Dropping requested beat...hold on a second.</div>

									<!-- Success alert -->
									<div id="alert-success" class="alert alert-success alert-hide">
										<span id="success-message"></span> Soon we'll all get to hear those delicious tunes.<br><br>
										Feel free to get right on it and send us another.
									</div>

									<!-- Failure alert -->
									<div id="alert-failure" class="alert alert-danger alert-hide">Something went wrong, but we're not sure what. Try again later...we'll have it fixed by then. Promise.</div>

									<!-- Drop that beat! -->
									<button id="drop-beat" class="btn btn-primary btn-lg btn-block"><span class="glyphicon glyphicon-cloud-uplad"></span> Add your song!</button>
								</div>
							</div>
						</div>
					</form>
				
			</div>
		</div>
	</div>
</div>

<script> $('#navbar-foffbox').addClass('active'); </script>
