<?php include('../basedir.php'); ?>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="wall.js"></script>
<script src="../js/global.js"></script>
<script src="../js/google-analytics.js"></script>

<style>
	::-webkit-scrollbar {
		width: 0 !important;
	}

	.tooltip-inner
	{
		background-color: #000 !important;
		border-color: #FFF !important;
		font-size:17px !important;
		max-width: 100% !important;
		width: auto !important;
		white-space:pre-wrap;
	}
	.tooltip.in
	{
		border-color: #FFF !important;
		filter: alpha(opacity=100) !important;
		opacity: 1.0 !important;
	}
</style>

<html>
	<head>
		<!-- Bootstrap CDN -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="style.css">
		<link rel="stylesheet" href="../css/style-navbar.css">
		<title>The Foffbox Wall</title>
	</head>
	<body style="background-color: #111 !important; background-image:none !important;">
		
		<?php include("../php/navbar.php"); ?>

		<h3 style="color:#DDD; text-align:center;">Enjoy. New beats drop on <strong>Saturday Nights</strong>.</h3><br>
		
		<div id="loading" style="color:#DDD; text-align:center;">Loading beats...<br><img src="img/loading.GIF"/><br><br><br></div>
		
		<div id="wall" style="color:#DDD;">
			<div id="nothing-here" style="text-align:center;">Nothing here yet. Check back Sunday morning.</div>
		</div>

	</body>
</html>

<!-- Start of StatCounter Code for Default Guide -->
<script type="text/javascript">
var sc_project=10056026; 
var sc_invisible=1; 
var sc_security="287ac542"; 
var scJsHost = (("https:" == document.location.protocol) ?
"https://secure." : "http://www.");
document.write("<sc"+"ript type='text/javascript' src='" +
scJsHost+
"statcounter.com/counter/counter.js'></"+"script>");
</script>

<script> $('#navbar-foffbox').addClass('active'); </script>
