<?php include('../../basedir.php'); ?> 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/greentext.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/google-analytics.js"></script>
<script src="player.js"></script>
<script src="modal-drop-beats.js"></script>

<html>
	<head>
		<!-- Bootstrap CDN -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="style.css">
		<title>Foffbox Radio</title>
	</head>
	<body style="background-color: #111 !important; background-image:none !important;">
		
		<?php include("../../navbar/navbar.phtml"); ?>
		
		<!-- Slider Bar (to select a song) -->
		<div class="row row-padding-fix">
			<div class="col-md-2 col-md-offset-5 center-col">
				<input id="request-slider" type="range" min="1" max="218" value="1" data-toggle="tooltip" title="Drag me. Jump beats. Have fun." data-toggle-position="right" />
			</div>
		</div><br>
		
		<!-- Toolbar -->
		<div class="row row-padding-fix">
			<div class="col-md-4 col-md-offset-4 center-col">
				<!-- Player buttons -->
				<div class="btn-group" role="toolbar">
					<a id="foffbox-player-first" class="btn btn-default foffbox-player-button" title="Back to First Beat"><span class="glyphicon glyphicon-fast-backward"></span></a>
					<a id="foffbox-player-prev" class="btn btn-default foffbox-player-button" title="Previous Beat"><span class="glyphicon glyphicon-backward"></span></a>
					<a id="foffbox-player-autoplay" class="btn btn-default foffbox-player-button" title="Toggle Autoplay"><span class="glyphicon glyphicon-retweet"></span></a>
					<a id="foffbox-player-shuffle" class="btn btn-default foffbox-player-button" title="Toggle Shuffle"><span class="glyphicon glyphicon-random"></span></a>
					<a id="foffbox-player-next" class="btn btn-default foffbox-player-button" title="Next Beat"><span class="glyphicon glyphicon-forward"></span></a>
					<a id="foffbox-player-last" class="btn btn-default foffbox-player-button" title="Last Submitted Beat"><span class="glyphicon glyphicon-fast-forward"></span></a>
				</div>
				
				<!-- Extra functions -->
				<div class="btn-group" role="toolbar">
					<a id="foffbox-player-drop" class="btn btn-default foffbox-player-button" title="Click to add your own beats to the radio!" data-toggle="modal" data-target="#drop-beats-modal"><span class="glyphicon glyphicon-fire"></span></a>
					<a id="foffbox-player-report" class="btn btn-default foffbox-player-button" title="Report Non-beat"><span class="glyphicon glyphicon-flag"></span></a>
				</div>
			</div>
		</div><br>
		
		<div id="loading" style="color:#DDD; text-align:center;">
			Serving up some more beats, sit tight...<br>
			<img src="img/loading.gif"/><br><br><br>
		</div>
		
		<div id="foffbox-player">
			<div class="row row-padding-fix">
				<div id="foffbox-player-left" class="col-md-5 col-md-offset-1">
					<div id="foffbox-player-video"></div>
				</div>
				
				<div id="foffbox-player-right" class="col-md-5">
				
					<!-- Message & details -->
					<blockquote id="foffbox-player-quote" style="margin-left: -15px;">
						<p>
							Something is broken.<br>
							No quotes to be found here. Huh.<br>
							Maybe Javascript's off?
						</p>
						<footer>The Foff</footer>
					</blockquote>
					
					<!-- Comment section -->
					<div class="row">
						<div id="comment-area">

							<!-- "Drop comment" box -->
							<div class="form-group">
								<textarea id="comment-field" class="form-control" type="text" name="messageBox" placeholder="Anything you want to say?" maxlength="250" rows="2" required></textarea><br>
								<a id="submit-comment" class="btn btn-block btn-primary" style="cursor:pointer;">
									<span class="glyphicon glyphicon-comment"></span> Drop that comment!
								</a>
							</div>
							
							<div id="comment-error" class="alert alert-danger"></div>
							
							<br>
							
							<!-- Comment thread -->
							<div id="comment-thread-wrapper">
								<h4>Recent comments</h4>
								<div id="comment-thread"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<?php include("modal-drop-beats.phtml"); ?>
		
	</body>
</html>

<script>
$('#navbar-foffbox').addClass('active');
</script>
