<?php include('../../basedir.php'); ?> 

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.0/jquery.validate.min.js"></script>
<script src="https://code.jquery.com/ui/1.11.1/jquery-ui.min.js"></script>
<script>
	$.widget.bridge('uitooltip', $.ui.tooltip);
</script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/greentext.js"></script>
<script src="<?php echo(BASEDIR); ?>/js/google-analytics.js"></script>
<script src="player.js"></script>
<script src="modal-drop-beats.js"></script>

<html>
	<head>
		<!-- Bootstrap CDN -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
		<link rel="stylesheet" href="style.css">
		<link rel="stylesheet" href="scrollbars.css">
		<link rel="stylesheet" href="popovers.css">
		<title>Foffbox Radio</title>
	</head>
	<body style="background-color: #111 !important; background-image:none !important;">
		
		<!-- Video layer -->
		<div id="foffbox-player-video"></div>
		
		<!-- Cover layer -->
		<div id="foffbox-player-video-cover">
		
			<!-- Player layer -->
			<div id="foffbox-player-right" class="col-md-5">

				<!-- Message & details -->
				<blockquote id="foffbox-player-quote">
					<p>
						Something is broken.<br>
						No quotes to be found here. Huh.<br>
						Maybe Javascript's off?
					</p>
					<footer>The Foff</footer>
				</blockquote>
				
				<!-- "Labels" section -->
				<div id="comment-labels">
					
				</div>

				<!-- Comment section -->
				<div class="row">
					<div id="comment-area">
					
						<!-- "Drop comment" box -->
						<div id="comment-group" class="form-group">
							<textarea id="comment-field" class="form-control" type="text" name="messageBox" placeholder="Anything you want to say?" maxlength="250" rows="2" required></textarea><br>
							<a id="submit-comment" class="btn btn-block btn-primary" style="cursor:pointer;">
								<span class="glyphicon glyphicon-comment"></span> Drop that comment!
							</a>
						</div>

						<div id="comment-error" class="alert alert-danger"></div>

						<br>

						<!-- Comment thread -->
						<div id="comment-thread-wrapper">
							<h4>Recent comments</h4>
							<div id="comment-thread"></div>
						</div>
					</div>
				</div>

			</div>
		
		</div>

		<div id="loading" style="color:#DDD; text-align:center; margin-top:25%;">
			<!-- Serving up some more beats, sit tight...<br> -->
			<img src="img/loading.gif"/>
		</div>
		
		<nav id="foffbox-toolbar" class="navbar navbar-default navbar-fixed-bottom" role="navigation" style="display:table;">
		
			<!-- Beat selector -->
			<div id="toolbar-left" class="btn-group" role="toolbar" style="position:absolute; left: 0; top: 0; height: 100%; z-index:3;">
				<a id="foffbox-player-first" class="btn btn-default foffbox-player-button" title="Back to First Beat"><span class="glyphicon glyphicon-fast-backward"></span></a>
				<a id="foffbox-player-prev" class="btn btn-default foffbox-player-button" title="Previous Beat"><span class="glyphicon glyphicon-backward"></span></a>
				<a id="foffbox-player-autoplay" class="btn btn-default foffbox-player-button" title="Toggle Autoplay"><span class="glyphicon glyphicon-retweet"></span></a>
				<a id="foffbox-player-play-pause" class="btn btn-default foffbox-player-button" title="Play"><span class="glyphicon glyphicon-play"></span></a>
				<a id="foffbox-player-shuffle" class="btn btn-default foffbox-player-button" title="Toggle Shuffle"><span class="glyphicon glyphicon-random"></span></a>
				<a id="foffbox-player-next" class="btn btn-default foffbox-player-button" title="Next Beat"><span class="glyphicon glyphicon-forward"></span></a>
				<a id="foffbox-player-last" class="btn btn-default foffbox-player-button" title="Last Submitted Beat"><span class="glyphicon glyphicon-fast-forward"></span></a>
			</div>
			
			<!--Title -->
			<div style="width: 100%; display:table-cell; vertical-align:middle;">
				<div id="title-ticker" class="marquee" style="position: relative; overflow: hidden;"><span id="title-ticker-inner"></span></div>
				<div style="text-align:center;"><img id="title-ticker-loading" src="img/loading.gif"/></div>
			</div>

			<!-- Extra functions -->
			<div id="toolbar-right" class="btn-group pull-right" role="toolbar" style="position:absolute; right: 0; top: 0; height: 100%; z-index:2;">
				<a id="foffbox-player-drop" class="btn btn-default foffbox-player-button" title="Add beat" data-toggle="modal" data-target="#drop-beats-modal"><span class="glyphicon glyphicon-cloud-upload"></span></a>
				<a id="foffbox-player-comments" class="btn btn-default foffbox-player-button" title="Comments"><span class="glyphicon glyphicon-comment"></span></a>
				<a id="foffbox-player-labels" class="btn btn-default foffbox-player-button" title="Filter by Song Type"><span class="glyphicon glyphicon-tags"></span></a>
				<a id="foffbox-player-volume" class="btn btn-default foffbox-player-button" title="Volume"><span class="glyphicon glyphicon-volume-up"></span></a>
				<a id="foffbox-player-quality" class="btn btn-default foffbox-player-button" title="Video Quality"><span class="glyphicon glyphicon-eye-open"></span></a>
				<a id="foffbox-player-report" class="btn btn-default foffbox-player-button" title="Report"><span class="glyphicon glyphicon-flag"></span></a>
				<a id="foffbox-player-home" class="btn btn-default foffbox-player-button" href="../" title="Foffbox"><span class="glyphicon glyphicon-home"></span></a>
			</div>
		</nav>

		<?php include("modal-drop-beats.phtml"); ?>
	</body>
</html>
