<!-- Some inline styles -->
<style>
#drop-beats-suggestion
{
	color: #3D72E3 !important;
	cursor: pointer;
	-moz-user-select: none; 
	-khtml-user-select: none; 
	-webkit-user-select: none; 
	-o-user-select: none;
}
</style>

<!-- Modal -->
<div id="select-labels-modal" class="modal fade" tabindex="-1" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">
				Hello world
			</div>
		</div>
	</div>
</div>